# Prueba de homogeneidad

Es una prueba aplicando la distribución Chi-cuadrada para verificar si una muestra de números son aleatorios o no.


In [7]:
from math import *
from scipy.stats import *   # Para usar funcion de densidad de chi cuadrada y función de distribucion acumulada chi cuadrada
import numpy as np

'''
  Aqui es donde se ponen los datos de la tabla
    |
    |
    v
'''

tabla = np.array([[15,10,15],[21,20,9]]) # Datos que da el problema

print("Datos del problema\n")
print(tabla)


# Codigo complementario para la tabla de contingecia
def suma_columna(A,columna):
  s = 0
  for i in range(A.shape[1]):
    for j in range(A.shape[0]):
      if columna==i:
        s+=tabla[j][i]
  return s


# Codigo de la tabla de contingencia para la prueba
class Tabla_de_contingencia:
  def t(A):
    t1 = np.zeros((A.shape[0]+1,1+A.shape[1]))  # Matriz vacia para luego ingresar los datos

    for i in range(A.shape[0]):       # Ingresar elementos en la nueva matriz
      for j in range(A.shape[1]):
        t1[i][j]=A[i][j]

    for k in range(A.shape[0]):           #suma de los renglones
      t1[k][A.shape[1]]=sum(A[k])

    for m in range(A.shape[1]):           #suma de las columnas
      t1[A.shape[0]][m]=suma_columna(A,m)
    return t1

  def n(A):     # tamaño de la muestra
    s=0
    for k in A:
      s+=sum(k)
    return s

print("Tabla con los totales de renglones y columnas\n",Tabla_de_contingencia.t(tabla))
print("Tamaño de la muestra: ",Tabla_de_contingencia.n(tabla),"\n")



# Codigo del estadistico de prueba \/
def estaditico_de_prueba(A,B):
  x_0=0
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      x_0+=(A[i][j]-(B[A.shape[0]][j]*B[i][A.shape[1]])/Tabla_de_contingencia.n(A))**2/((B[A.shape[0]][j]*B[i][A.shape[1]])/Tabla_de_contingencia.n(A))
  return x_0


titulo=" Calculos del problema "
print(titulo.center(60,"="),"\n")


print('Estadistico de prueba:',estaditico_de_prueba(tabla,Tabla_de_contingencia.t(tabla)))


'''
  Codigo del punto critico
  Para obtener el punto critico se utilizan la funcion de densidad y de distribucion acumulada de la distribución chi cuadrada que estan
  en la libreria
'''
class Punto_critico:
  x = 0
  n = 0
  def r(v,alfa):
    if Punto_critico.n==0:
      Punto_critico.x=v
      Punto_critico.n+=1
      return Punto_critico.x
    if Punto_critico.n>0:
      Punto_critico.n+=1
      Punto_critico.x-=(chi2.cdf(Punto_critico.x,v)-1+alfa)/chi2.pdf(Punto_critico.x,v)
      return Punto_critico.x

v = (tabla.shape[0]-1)*(tabla.shape[1]-1) # v grados de libertad
print("Grados de libertad",v)


alpha = 0.05  # nivel de significancia
print("Nivel de significación",alpha)

for i in range(10):
	Punto_critico.r(v,alpha)

print('Punto critico:',Punto_critico.r(v,alpha)) # resultado del punto critico


if estaditico_de_prueba(tabla,Tabla_de_contingencia.t(tabla)) > Punto_critico.r(v,0.05):
  print("Se rechaza la hipotesis de homogeneidad")
else:
  print("Se acepta la hipotesis de homogenidad")


Datos del problema

[[15 10 15]
 [21 20  9]]
Tabla con los totales de renglones y columnas
 [[15. 10. 15. 40.]
 [21. 20.  9. 50.]
 [36. 30. 24.  0.]]
Tamaño de la muestra:  90 

================== Calculos del problema =================== 

Estadistico de prueba: 4.78125
Grados de libertad 2
Nivel de significación 0.05
Punto critico: 5.991464547107983
Se acepta la hipotesis de homogenidad
