# Prueba de homogeneidad $\chi^2$

Es una prueba aplicando la distribución Chi-cuadrada para verificar si una muestra de números son aleatorios o no.

Aqui es donde se da la solución del problema 3 y 4 pero primero se pondra el codigo del programa y luego las soluciones.


In [49]:
from math import *
from scipy.stats import * # Para usar la funcion de densidad y de distribucion acumulada de chi cuadrada
import numpy as np

'''
  Aqui es donde se ponen los datos de la tabla editando los valores de la tabla
    |
    |
    v
'''
tabla = np.array([[15,10,15],[21,20,9]]) # Datos que da el problema (aqui solo se pone una tabla de )

print("Datos del problema\n")
print(tabla)

alpha = 0.05  # nivel de significancia
print("\nNivel de significación",alpha)


# Codigo complementario para la tabla de contingecia
def suma_columna(A,columna):
  s = 0
  for i in range(A.shape[1]):
    for j in range(A.shape[0]):
      if columna==i:
        s+=A[j][i]
  return s


# Codigo de la tabla de contingencia para la prueba
class Tabla_de_contingencia:
  def t(A):
    t1 = np.zeros((A.shape[0]+1,1+A.shape[1]))  # Matriz vacia para luego ingresar los datos

    for i in range(A.shape[0]):       # Ingresar elementos en la nueva matriz
      for j in range(A.shape[1]):
        t1[i][j]=A[i][j]

    for k in range(A.shape[0]):           #suma de los renglones
      t1[k][A.shape[1]]=sum(A[k])

    for m in range(A.shape[1]):           #suma de las columnas
      t1[A.shape[0]][m]=suma_columna(A,m)
    return t1

  def v(A):     #grados de libertad
    return (A.shape[0]-1)*(A.shape[1]-1)

  def n(A):     # tamaño de la muestra
    s=0
    for k in A:
      s+=sum(k)
    return s

print("\nTabla con los totales de renglones y columnas\n")
print(Tabla_de_contingencia.t(tabla))


print("\nTamaño de la muestra: ",Tabla_de_contingencia.n(tabla),"\n")



# Codigo del estadistico de prueba
def estaditico_de_prueba(A,B):
  x_0=0
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      x_0+=(A[i][j]-(B[A.shape[0]][j]*B[i][A.shape[1]])/Tabla_de_contingencia.n(A))**2/((B[A.shape[0]][j]*B[i][A.shape[1]])/Tabla_de_contingencia.n(A))
  return x_0


titulo=" Calculos del problema "
print(titulo.center(60,"="),"\n")


print('Estadistico de prueba:',estaditico_de_prueba(tabla,Tabla_de_contingencia.t(tabla)))


'''
  Codigo del punto critico.

  Para obtener el punto critico se utiliza la funcion de densidad y de distribucion acumulada
  de la distribución chi cuadrada que estan en la libreria scipy.stats y para obtener los puntos
  se emplea el método de newton-raphson.
'''
class Punto_critico:
  x = 1
  n = 0
  def r(v,alfa):
    if Punto_critico.n==0:
      Punto_critico.n+=1
      return Punto_critico.x
    if Punto_critico.n>0:
      Punto_critico.n+=1
      Punto_critico.x-=(chi2.cdf(Punto_critico.x,v)-1+alfa)/chi2.pdf(Punto_critico.x,v)
      return Punto_critico.x

for i in range(10):
	Punto_critico.r(Tabla_de_contingencia.v(tabla),alpha)

print('Punto critico:',Punto_critico.r(Tabla_de_contingencia.v(tabla),alpha)) # resultado del punto critico


print("Grados de libertad",Tabla_de_contingencia.v(tabla))


if estaditico_de_prueba(tabla,Tabla_de_contingencia.t(tabla)) > Punto_critico.r(Tabla_de_contingencia.v(tabla),0.05):
  print("Se rechaza la hipotesis de homogeneidad")
else:
  print("Se acepta la hipotesis de homogenidad")


Datos del problema

[[15 10 15]
 [21 20  9]]

Nivel de significación 0.05

Tabla con los totales de renglones y columnas

[[15. 10. 15. 40.]
 [21. 20.  9. 50.]
 [36. 30. 24.  0.]]

Tamaño de la muestra:  90 

================== Calculos del problema =================== 

Estadistico de prueba: 4.78125
Punto critico: 5.991464547107982
Grados de libertad 2
Se acepta la hipotesis de homogenidad


3.- Realice una prueba de uniformidad $\chi ^2$ a los números de la tabla siguiente, con un
nivel de aceptación del 95 %

$
\begin{matrix}
38 & 33 & 25 & 5 & 69 & 35 & 98 & 52 & 12 & 79 \\
50 & 46 & 95 & 42 & 49 & 11 & 78 & 34 & 2 & 43 \\
 7 & 50 &  5 & 91 & 77 & 18 & 21 &  4 & 17 & 62 \\
91 & 36 & 48 & 88 & 52 & 76 & 99 & 73 & 82 & 90 \\
\end{matrix}
$

## Solución

Pasamos todos los datos a una matriz y se imprime la tabla de contingencia, grados de libertad, estadistico de prueba y en este caso el valor de alfa es $\alpha=0.05$ que se usará para el punto critico.

In [50]:
tabla3 = np.array(
[[38 , 33 , 25,  5 , 69 , 35 , 98 , 52 , 12 , 79],
 [50 , 46 , 95, 42 , 49 , 11 , 78 , 34 , 2  , 43],
 [ 7 , 50 ,  5, 91 , 77 , 18 , 21 ,  4 , 17 , 62],
 [91 , 36 , 48, 88 , 52 , 76 , 99 , 73 , 82 , 90]])

alfa3=0.05

print("valor de alfa:",alfa3)

print("\nTabla de contingencia".ljust(60,"="),"\n")
print(Tabla_de_contingencia.t(tabla3))

print("\nGrados de libertda".ljust(60,"="),"\n")
print(Tabla_de_contingencia.v(tabla3))

print("\nEstadistico de prueba".ljust(60,"="),"\n")
print(estaditico_de_prueba(tabla3,Tabla_de_contingencia.t(tabla3)))

print("\nPunto critico".ljust(60,"="),"\n")
for i1 in range(10):
  print(Punto_critico.r(100,alfa3))

print(Punto_critico.r(26,alfa3))

valor de alfa: 0.05

Tabla de contingencia====================================== 

[[ 38.  33.  25.   5.  69.  35.  98.  52.  12.  79. 446.]
 [ 50.  46.  95.  42.  49.  11.  78.  34.   2.  43. 450.]
 [  7.  50.   5.  91.  77.  18.  21.   4.  17.  62. 352.]
 [ 91.  36.  48.  88.  52.  76.  99.  73.  82.  90. 735.]
 [186. 165. 173. 226. 247. 140. 296. 163. 113. 274.   0.]]

Grados de libertda========================================= 

27

Estadistico de prueba====================================== 

498.4633948363388

Punto critico============================================== 

1.0357180719007534e+41
-inf
nan
nan
nan
nan
nan
nan
nan
nan
nan


<ipython-input-49-3806f4ddd915>:95: RuntimeWarning: divide by zero encountered in scalar divide
  Punto_critico.x-=(chi2.cdf(Punto_critico.x,v)-1+alfa)/chi2.pdf(Punto_critico.x,v)
<ipython-input-49-3806f4ddd915>:95: RuntimeWarning: invalid value encountered in scalar subtract
  Punto_critico.x-=(chi2.cdf(Punto_critico.x,v)-1+alfa)/chi2.pdf(Punto_critico.x,v)
