# Prueba de homogeneidad $\chi^2$

Es una prueba aplicando la distribución Chi-cuadrada para verificar si una muestra de números son aleatorios o no.

Aqui es donde se da la solución del problema 3 y 4 pero primero se pondra el codigo del programa y luego las soluciones.


In [ ]:
from math import *
from scipy.stats import * # Para usar la funcion de densidad y de distribucion acumulada de chi cuadrada
import numpy as np

# A continuacion tramo de todas las funciones que se van a usar

# Codigo complementario para la tabla de contingecia <------------------------------------------------------------------
def suma_columna(A,columna):
  s = 0
  for i in range(A.shape[1]):
    for j in range(A.shape[0]):
      if columna==i:
        s+=A[j][i]
  return s

# Codigo de la tabla de contingencia para la prueba <------------------------------------------------------------------
class Tabla_de_contingencia:
  def t(A):
    t1 = np.zeros((A.shape[0]+1,1+A.shape[1]))  # Matriz vacia para luego ingresar los datos

    for i in range(A.shape[0]):       # Ingresar elementos en la nueva matriz
      for j in range(A.shape[1]):
        t1[i][j]=A[i][j]

    for k in range(A.shape[0]):           #suma de los renglones
      t1[k][A.shape[1]]=sum(A[k])

    for m in range(A.shape[1]):           #suma de las columnas
      t1[A.shape[0]][m]=suma_columna(A,m)
    return t1

  def v(A):     #grados de libertad
    return (A.shape[0]-1)*(A.shape[1]-1)

  def n(A):     # tamaño de la muestra
    s=0
    for k in A:
      s+=sum(k)
    return s

# Codigo del estadistico de prueba <------------------------------------------------------------------
def estaditico_de_prueba(A,B):
  x_0=0
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      x_0+=(A[i][j]-(B[A.shape[0]][j]*B[i][A.shape[1]])/Tabla_de_contingencia.n(A))**2/((B[A.shape[0]][j]*B[i][A.shape[1]])/Tabla_de_contingencia.n(A))
  return x_0

'''
  Codigo del punto critico.  <------------------------------------------------------------------

  Para obtener el punto critico se utiliza la funcion de densidad y de distribucion acumulada
  de la distribución chi cuadrada que estan en la libreria scipy.stats y para obtener los puntos
  se emplea el método de newton-raphson en este caso se programo de manera recursiva, claro nada
  eficiente, ni rapido pero al menos funcional.
'''
def newton_rapson(n,v,alfa):
    if n==0:
        return v   # punto de partida de propone x_0 = v el mismo grado de grado de libertad
    if n>0:
        return newton_rapson(n-1,v,alfa)-(chi2.cdf(newton_rapson(n-1,v,alfa),v)-1+alfa)/chi2.pdf(newton_rapson(n-1,v,alfa),v)

def punto_critico(v,alfa):
    for i in range(7):
        newton_rapson(i,v,alfa)
    return newton_rapson(i,v,alfa)


'''
  Aqui es donde se ponen los datos de la tabla
    |
    |
    v
'''
tabla = np.array([[15,10,15],[21,20,9]]) # <--------------------------- Tabla de valores

print("Datos del problema\n")
print(tabla)

alpha = 0.05  # nivel de significancia


print("\nTabla con los totales de renglones y columnas\n")
print(Tabla_de_contingencia.t(tabla))

print("\nTamaño de la muestra: ",Tabla_de_contingencia.n(tabla),"\n")

titulo=" Calculos del problema "
print(titulo.center(60,"="),"\n")

print("\nNivel de significación",alpha)

print("Grados de libertad",Tabla_de_contingencia.v(tabla))

print('Estadistico de prueba:',estaditico_de_prueba(tabla,Tabla_de_contingencia.t(tabla)))

print('Punto critico:',punto_critico(Tabla_de_contingencia.v(tabla),alpha)) # resultado del punto critico

if estaditico_de_prueba(tabla,Tabla_de_contingencia.t(tabla)) > punto_critico(Tabla_de_contingencia.v(tabla),alpha):
  print("Se rechaza la hipotesis de homogeneidad")
else:
  print("Se acepta la hipotesis de homogenidad")


Datos del problema

[[15 10 15]
 [21 20  9]]

Tabla con los totales de renglones y columnas

[[15. 10. 15. 40.]
 [21. 20.  9. 50.]
 [36. 30. 24.  0.]]

Tamaño de la muestra:  90 

================== Calculos del problema =================== 


Nivel de significación 0.05
Grados de libertad 2
Estadistico de prueba: 4.78125
Punto critico: 5.991464547052784
Se acepta la hipotesis de homogenidad


# 3.- Realice una prueba de uniformidad $\chi ^2$ a los números de la tabla siguiente, con un nivel de aceptación del 95 %

$$
\begin{matrix}
38 & 33 & 25 & 5 & 69 & 35 & 98 & 52 & 12 & 79 \\
50 & 46 & 95 & 42 & 49 & 11 & 78 & 34 & 2 & 43 \\
 7 & 50 &  5 & 91 & 77 & 18 & 21 &  4 & 17 & 62 \\
91 & 36 & 48 & 88 & 52 & 76 & 99 & 73 & 82 & 90 \\
\end{matrix}
$$

## Solución

Pasamos todos los datos a una matriz y se imprime la tabla de contingencia, grados de libertad, estadistico de prueba y en este caso el valor de alfa es $\alpha=0.05$ que se usará para el punto critico.

In [ ]:
tabla3 = np.array(
[[38 , 33 , 25,  5 , 69 , 35 , 98 , 52 , 12 , 79],
 [50 , 46 , 95, 42 , 49 , 11 , 78 , 34 , 2  , 43],
 [ 7 , 50 ,  5, 91 , 77 , 18 , 21 ,  4 , 17 , 62],
 [91 , 36 , 48, 88 , 52 , 76 , 99 , 73 , 82 , 90]])

alfa3=0.05

print("valor de alfa:",alfa3)

print("\nTabla de contingencia".ljust(60,"="),"\n")
print(Tabla_de_contingencia.t(tabla3))

print("\ntamaño de la muestra".ljust(60,"="),"\n")
print(Tabla_de_contingencia.n(tabla3))

print("\nGrados de libertad".ljust(60,"="),"\n")
print(Tabla_de_contingencia.v(tabla3))

print("\nEstadistico de prueba".ljust(60,"="),"\n")
print(estaditico_de_prueba(tabla3,Tabla_de_contingencia.t(tabla3)))

print("\nPunto critico".ljust(60,"="),"\n")
print(punto_critico(Tabla_de_contingencia.v(tabla3),alfa3))


print("\nCriterio de decision".ljust(60,"="),"\n")
if estaditico_de_prueba(tabla3,Tabla_de_contingencia.t(tabla3)) > punto_critico(Tabla_de_contingencia.v(tabla3),alfa3):
  print("Se rechaza la hipotesis de homogeneidad")
else:
  print("Se acepta la hipotesis de homogenidad")


valor de alfa: 0.05

Tabla de contingencia====================================== 

[[ 38.  33.  25.   5.  69.  35.  98.  52.  12.  79. 446.]
 [ 50.  46.  95.  42.  49.  11.  78.  34.   2.  43. 450.]
 [  7.  50.   5.  91.  77.  18.  21.   4.  17.  62. 352.]
 [ 91.  36.  48.  88.  52.  76.  99.  73.  82.  90. 735.]
 [186. 165. 173. 226. 247. 140. 296. 163. 113. 274.   0.]]

tamaño de la muestra======================================= 

1983

Grados de libertad========================================= 

27

Estadistico de prueba====================================== 

498.4633948363388

Punto critico============================================== 

40.113272069412595

Criterio de decision======================================= 

Se rechaza la hipotesis de homogeneidad


# 4.- Realice una prueba de uniformidad $\chi ^2$ a los números de la tabla siguiente, con un nivel de aceptación del 95 %

$$
\begin{matrix}
0.8797 & 0.3884 & 0.6289 & 0.8750 & 0.5999 & 0.8589 & 0.9996 & 0.2415 & 0.3808 & 0.9606 \\
0.9848 & 0.3469 & 0.7977 & 0.5844 & 0.8147 & 0.6431 & 0.7387 & 0.5613 & 0.0318 & 0.7401 \\
0.4557 & 0.1592 & 0.8536 & 0.8846 & 0.3410 & 0.1492 & 0.8681 & 0.5291 & 0.3188 & 0.5992 \\
0.9170 & 0.2204 & 0.5991 & 0.5461 & 0.5739 & 0.3254 & 0.0856 & 0.2258 & 0.4603 & 0.5027 \\
0.8376 & 0.6235 & 0.3681 & 0.2088 & 0.1525 & 0.2006 & 0.4720 & 0.4272 & 0.6360 & 0.0954
\end{matrix}
$$

## Solución

Para solamente manejar numeros enteros multiplicamos todos los numeros por 10000 y pasamos todos los datos a una matriz y se imprime la tabla de contingencia, grados de libertad, estadistico de prueba y en este caso el valor de alfa es $\alpha=0.05$ que se usará para el punto critico.

In [ ]:
t4 = np.array(
[[0.8797 , 0.3884 , 0.6289 , 0.8750 , 0.5999 , 0.8589 , 0.9996 , 0.2415 , 0.3808 , 0.9606 ],
[0.9848 , 0.3469 , 0.7977 , 0.5844 , 0.8147 , 0.6431 , 0.7387 , 0.5613 , 0.0318 , 0.7401 ],
[0.4557 , 0.1592 , 0.8536 , 0.8846 , 0.3410 , 0.1492 , 0.8681 , 0.5291 , 0.3188 , 0.5992 ],
[0.9170 , 0.2204 , 0.5991 , 0.5461 , 0.5739 , 0.3254 , 0.0856 , 0.2258 , 0.4603 , 0.5027 ],
[0.8376 , 0.6235 , 0.3681 , 0.2088 , 0.1525 , 0.2006 , 0.4720 , 0.4272 , 0.6360 , 0.0954 ]])

tabla4 =  1000*t4

alfa4=0.05

print("valor de alfa:",alfa4)

print("\nTabla de contingencia".ljust(60,"="),"\n")
print(Tabla_de_contingencia.t(tabla4))

print("\nGrados de libertad".ljust(60,"="),"\n")
print(Tabla_de_contingencia.v(tabla4))

print("\nEstadistico de prueba".ljust(60,"="),"\n")
print(estaditico_de_prueba(tabla4,Tabla_de_contingencia.t(tabla4)))

print("\nPunto critico".ljust(60,"="),"\n")
print(punto_critico(Tabla_de_contingencia.v(tabla4),alfa4))


print("\nCriterio de decision".ljust(60,"="),"\n")
if estaditico_de_prueba(tabla4,Tabla_de_contingencia.t(tabla4)) > punto_critico(Tabla_de_contingencia.v(tabla4),alfa4):
  print("Se rechaza la hipotesis de homogeneidad")
else:
  print("Se acepta la hipotesis de homogenidad")


valor de alfa: 0.05

Tabla de contingencia====================================== 

[[ 879.7  388.4  628.9  875.   599.9  858.9  999.6  241.5  380.8  960.6
  6813.3]
 [ 984.8  346.9  797.7  584.4  814.7  643.1  738.7  561.3   31.8  740.1
  6243.5]
 [ 455.7  159.2  853.6  884.6  341.   149.2  868.1  529.1  318.8  599.2
  5158.5]
 [ 917.   220.4  599.1  546.1  573.9  325.4   85.6  225.8  460.3  502.7
  4456.3]
 [ 837.6  623.5  368.1  208.8  152.5  200.6  472.   427.2  636.    95.4
  4021.7]
 [4074.8 1738.4 3247.4 3098.9 2482.  2177.2 3164.  1984.9 1827.7 2898.
     0. ]]

Grados de libertad========================================= 

36

Estadistico de prueba====================================== 

4302.095964227874

Punto critico============================================== 

50.99846016571

Criterio de decision======================================= 

Se rechaza la hipotesis de homogeneidad
