# Ruina del jugador

Se reúnen dos personas para un juego, cada jugador empieza con una determinada cantidad de dinero, si el primer jugador pierde le tiene que dar un peso al otro, pero si el primer jugador gana el otro jugador le tiene que dar un peso a él, la partida termina cuando el primer jugador tenga todo el dinero del otro o cuando llegue a la quiebra.

Para el siguiente código se definen las siguientes funciones.

``jugada(p)`` tiene como parámetro ``p`` donde $0<p<1$ y es la probabilidad de que el primer jugador gane un peso y su probabilidad de perder un peso es $1-p$.

Expresado de forma simbólica la variable aleatoria que sigue la función ``jugada(p)`` es:

$$P(X=x)= \left\{ \begin{array}{lcc}
p & \text{si} & x=1 \\ \\
1-p & \text{si} & x=-1
\end{array} \right.$$

``partida(p1,p2)`` tiene como parametros:


*   ``p1``: Cantidad de dinero del jugador uno.
*   ``p2``: Cantidad de dinero del jugador dos.

Lo que regresa la función es una lista de la cantidad de dinero que tiene el primer jugador durante toda una partida completa entre ambos jugadores. La función termina cuando el primer jugador gana todo el dinero o llega a la quiebra.

Lo anterior sería una representación matemática de la función, pero respecto a este juego nos podemos hacer la pregunta: ¿Cuál es la probabilidad de que el primer jugador gane todo el dinero del otro jugador?

Para ello, se escribe el código de las funciones y se realizan unas cuantas simulaciones.  A continuación, se va a simular una partida donde ambos jugadores tienen la misma cantidad de dinero, que en este caso sería $\$2$ pesos, pero el primer jugador tiene una probabilidad $1/3$ de ganar un peso.

In [6]:
from random import random
import numpy as np

def jugada(p):
	x = random()
	if x<=p:
		return 1     # Gano un peso
	else:
		return -1    # Perdio un peso

def partida(p1,p2):
	v = p1+p2
	l = []
	for i in range(1000000):
		l.append(p1)
		p1+=jugada(1/3)   #  p = 1/3
		if p1==0:
			l.append(p1)
			break
		elif p1==v:
			l.append(p1)
			break
	return l

print(partida(2,2))

[2, 3, 2, 3, 2, 1, 2, 1, 2, 1, 0]


Ahora vamos a simular 5 partidas.

In [15]:
for i in range(5):
  print(partida(2,2))

[2, 1, 2, 1, 0]
[2, 1, 0]
[2, 3, 2, 3, 2, 1, 2, 1, 2, 1, 0]
[2, 1, 0]
[2, 3, 4]


Para resolver la pregunta de cuál es la probabilidad de que el primer jugador gane todo el dinero lo que se hará es realizar muchas simulaciones y contar el número de victorias que tuvo, en este caso el primer jugador gana la partida si tiene un total de $\$4$ los $\$2$ más los $\$2$ del otro jugador.

A continuación se realizan, 100000 simulaciones y el número de victorias se va a dividir entre el número de simulaciones que se hicieron y el resultado será la probabilidad de éxito del primer jugador.

In [21]:
victorias = 0
n = 100000      # numero de partidas
for i in range(n):
	v = partida(2,2)
	if 4 in v:
		victorias += 1

print("Probabilidad de ganar:",victorias/n)

Probabilidad de ganar: 0.20076


Esta solución a la pregunta se realizó mediante simulación, pero ahora se resolverá este problema de manera analítica.

La matriz de transicion queda de la siguiente manera:

$$\begin{pmatrix}
1 & 0 & 0 & 0 & 0 \\
\frac{2}{3} & 0 & \frac{1}{3} & 0 & 0\\
0 & \frac{2}{3} & 0 & \frac{1}{3} & 0\\
0 & 0 & \frac{2}{3} & 0 & \frac{1}{3}\\
0 & 0 & 0 & 0 & 1 \\
\end{pmatrix}$$

Para el primer reglón que vendría siendo el estado donde el primer jugador llega a la ruina su probabilidad de llegar a la ruina es 1 y su probabilidad de ganar un peso o de ganar 2 o más es cero, puesto que el jugador se ha quedado sin dinero y el juego acaba cuando uno de los dos jugadores se queda sin dinero y por ende se escriben ceros en las demás entradas.

Cuando el primer jugador tiene solo un peso, la probabilidad son las siguientes: probabilidad de $1/3$ de tener $\$2$ y $2/3$ para que pierda un peso.

Cuando el primer jugador tiene dos pesos, las probabilidades son las siguientes: probabilidad de $1/3$ para tener $\$3$ y $2/3$ para que pierda un peso.

Cuando el primer jugador tiene tres pesos, las probabilidades son las siguientes: probabilidad de $1/3$ para tener $\$4$ y $2/3$ para que pierda un peso.

Por último, cuando el jugador gana, su probabilidad es de 1, puesto que ya tiene todo el dinero del otro jugador y termina el juego.

Para hallar la probabilidad de ganar se resuelve el siguiente sistema de ecuaciones.

$$
\left. \begin{array}{l}
\pi_{04}=0 \\
\pi_{14}=\frac{2}{3}\pi_{04}+\frac{1}{3}\pi_{24} \\
\pi_{24}=\frac{2}{3}\pi_{14}+\frac{1}{3}\pi_{34} \\
\pi_{34}=\frac{2}{3}\pi_{24}+\frac{1}{3}\pi_{44} \\
\pi_{44}=1 \\
\end{array} \right.$$

Resolvemos el sistema para $\pi_{24}$, puesto que en nuestro caso el primer jugador inicia con $\$2$ y se desea la probabilidad de que obtenga $\$4$.

$\pi_{24}=\frac{2}{3}(\frac{2}{3}\pi_{04}+\frac{1}{3}\pi_{24})+\frac{1}{3}(\frac{2}{3}\pi_{24}+\frac{1}{3}\pi_{44})$


$\pi_{24}=\frac{2}{9}\pi_{24}+\frac{2}{9}\pi_{24}+\frac{1}{9}$

$\frac{5}{9}\pi_{24}=\frac{1}{9}$

$\pi_{24}=\frac{1}{5}=0.2$

Esta es solo una manera de resolver el problema. Otra manera de resolver el problema es la siguiente:


Se dice que se llega a un estado de probabilidades estable cuando:

$$\lim_{n \to \infty}A^n=p$$


In [27]:
import numpy as np

A = np.array([[1,0,0,0,0],
              [2/3,0,1/3,0,0],
              [0,2/3,0,1/3,0],
              [0,0,2/3,0,1/3],
              [0,0,0,0,1]])

print(A)
print(np.round(np.linalg.matrix_power(A,30),2))

[[1.         0.         0.         0.         0.        ]
 [0.66666667 0.         0.33333333 0.         0.        ]
 [0.         0.66666667 0.         0.33333333 0.        ]
 [0.         0.         0.66666667 0.         0.33333333]
 [0.         0.         0.         0.         1.        ]]
[[1.   0.   0.   0.   0.  ]
 [0.93 0.   0.   0.   0.07]
 [0.8  0.   0.   0.   0.2 ]
 [0.53 0.   0.   0.   0.47]
 [0.   0.   0.   0.   1.  ]]
